<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>AillGameplaySuite</AssemblyName>
    <RootNamespace>AillGameplaySuite</RootNamespace>
    <Version>0.1.0</Version>
    <FileVersion>0.1.0.0</FileVersion>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <Deterministic>true</Deterministic>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bannerlord.ReferenceAssemblies" Version="1.4.7.117484" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
